version: "3"

networks:
  registrocontable-net:
    external: true

services:
  movimientos-service:
    image: "registro-contable/movimientos-service:${TAG}"
    container_name: movimientos-service
    networks:
      - registrocontable-net
    environment:
      - spring.cloud.config.profile=development
      - spring.cloud.config.uri=http://192.168.1.5:8888